
name: Train Model and Save Output

on:
  push:
    branches:
      - main  # 根据需要调整分支名称

jobs:
  train-and-save-model:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'  # 根据需要选择Python版本
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 假设所有依赖都在requirements.txt中列出

      - name: Train model and save output
        run: |
          python train.py 
          # 假设train.py脚本会在当前工作目录下生成.pth文件

      - name: Upload model
        uses: actions/upload-artifact@v2
        with:
          name: model-output
          path: ./*.pth
          # 如果.pth文件被保存在特定目录下，请适当调整path


